### ISSUE TITLE
support for custom formatting

### ISSUE THREAD

**Issue by SmilingPeace** [RappyLabyAddons/LabyChat-Utils#13]
It would be desirable to be able to customize the chat formatting yourself. Custom color codes or even color gradients are welcome.

I would be very grateful for the update!

**Comment by RappyTV** [comment]
I was just thinking about the best way to implement this. However, I have realized that the implementation of using custom color codes in the components is quite imperformant and will therefore not be accepted in the store.

**Comment by SmilingPeace** [comment]
maybe you can do it with the default color codes then?
