### ISSUE TITLE
Autocomplete names on message

### ISSUE THREAD

**Issue by PenT1x** [RappyLabyAddons/LabyChat-Utils#16]
`/lcu message pe` could tab autocomplete `PenT1x`.
Is should just try to autocomplete your labymod friends, because some players do not have names that are easy to just type because they have like 20 "i" in a row, or some weird name.

**Comment by RappyTV** [comment]
Hey! I would love to implement autocompletions but unfortunately autocompletions are not supported by LabyMod (yet?). As soon as there is a way to use autocompletions I will reopen this issue.
